
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-uri: <BASE64_ENCODED_MONGO_URI>
#kubectl create secret generic mongodb-connection-string-secret --from-literal=connection-string='your-mongo-connection-string'
