

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL2Nvc21vc2Rldm9wczp3UUFaTjNMQ1lrQm9WZEhybE1od3VCbXdOeU1Lb3Q2TkI5Q0JFWHoyMnZnZEVYU3lSNFNLbGVodVB2SUw5M3BPSkpQN20zc3loeVk4QUNEYkZLVlIyZz09QGNvc21vc2Rldm9wcy5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUBjb3Ntb3NkZXZvcHNA
#kubectl create secret generic mongodb-connection-string-secret --from-literal=connection-string='your-mongo-connection-string'
